### GET ALL PRODUCTS

GET http://localhost:3000/api/products HTTP/1.1

### GET SINGLE PRODUCT
GET http://localhost:3000/api/products/<PRODUCT_ID> HTTP/1.1
# GET http://localhost:3000/api/products/67d088b7686fbb098a850fc6 HTTP/1.1

### CREATE PRODUCT
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

{
"title": "add_product_by_create_method_1",
"price": "500",
"image": "image_url_of_product",
"details": "add_product_by_create_method"
}


### UPDATE PRODUCT
PUT http://localhost:3000/api/products/<product_id> HTTP/1.1
# PUT http://localhost:3000/api/products/67d08e1007cde81c736ed3ea HTTP/1.1
Content-Type: application/json

{
"title": "add_product_by_update_method_1",
"price": "5000",
"image": "update_image_url_of_product",
"details": "add_product_by_update_method"
}

### DELETE PRODUCT
DELETE http://localhost:3000/api/products/<product_id> HTTP/1.1
# DELETE http://localhost:3000/api/products/67d08e1007cde81c736ed3ea HTTP/1.1